import os
import json
import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak, KeepTogether,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.lib.colors import HexColor
from reportlab.pdfgen import canvas

# ── Renkler ──────────────────────────────────────────────────────────────────
C_DARK     = HexColor("#0d1117")
C_ACCENT   = HexColor("#e63946")
C_BLUE     = HexColor("#457b9d")
C_LIGHT_BG = HexColor("#f8f9fa")
C_BORDER   = HexColor("#dee2e6")
C_TEXT     = HexColor("#212529")
C_MUTED    = HexColor("#6c757d")
C_WHITE    = colors.white

C_CRIT     = HexColor("#dc2626")
C_CRIT_BG  = HexColor("#fef2f2")
C_HIGH     = HexColor("#ea580c")
C_HIGH_BG  = HexColor("#fff7ed")
C_MED      = HexColor("#ca8a04")
C_MED_BG   = HexColor("#fefce8")
C_LOW      = HexColor("#16a34a")
C_LOW_BG   = HexColor("#f0fdf4")
C_INFO     = HexColor("#2563eb")
C_INFO_BG  = HexColor("#eff6ff")

PAGE_W, PAGE_H = A4
MARGIN = 18 * mm


def sev_color(sev: str):
    return {
        "CRITICAL": (C_CRIT, C_CRIT_BG),
        "HIGH":     (C_HIGH, C_HIGH_BG),
        "MEDIUM":   (C_MED,  C_MED_BG),
        "LOW":      (C_LOW,  C_LOW_BG),
        "INFO":     (C_INFO, C_INFO_BG),
    }.get(sev.upper(), (C_MUTED, C_LIGHT_BG))


def sev_order(sev: str) -> int:
    return {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}.get(sev.upper(), 9)


# ── Header/Footer ─────────────────────────────────────────────────────────────
class ReportCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        self._info = kwargs.pop("doc_info", {})
        canvas.Canvas.__init__(self, *args, **kwargs)
        self._saved = []

    def showPage(self):
        self._saved.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total = len(self._saved)
        for state in self._saved:
            self.__dict__.update(state)
            self._draw_chrome(total)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def _draw_chrome(self, total):
        p = self._pageNumber
        w, h = A4

        if p == 1:
            # Kapak banner
            self.setFillColor(C_DARK)
            self.rect(0, h - 68*mm, w, 68*mm, fill=1, stroke=0)
            self.setFillColor(C_ACCENT)
            self.rect(0, h - 68*mm, 3*mm, 68*mm, fill=1, stroke=0)
            self.setFillColor(C_WHITE)
            self.setFont("Helvetica-Bold", 28)
            self.drawString(MARGIN, h - 26*mm, "GREYPHANTOM")
            self.setFont("Helvetica", 11)
            self.setFillColor(HexColor("#a8dadc"))
            self.drawString(MARGIN, h - 36*mm, "Automated Pentest Report")
            self.setFont("Helvetica-Bold", 13)
            self.setFillColor(C_WHITE)
            self.drawString(MARGIN, h - 50*mm, self._info.get("target", ""))
            self.setFont("Helvetica", 9)
            self.setFillColor(HexColor("#adb5bd"))
            self.drawString(MARGIN, h - 58*mm, self._info.get("date", ""))
            self.drawRightString(w - MARGIN, h - 58*mm, "CONFIDENTIAL")
        else:
            self.setFillColor(C_DARK)
            self.rect(0, h - 13*mm, w, 13*mm, fill=1, stroke=0)
            self.setFillColor(C_ACCENT)
            self.rect(0, h - 13*mm, 3*mm, 13*mm, fill=1, stroke=0)
            self.setFont("Helvetica-Bold", 8)
            self.setFillColor(C_WHITE)
            self.drawString(MARGIN, h - 7.5*mm, "GREYPHANTOM")
            self.setFont("Helvetica", 8)
            self.setFillColor(HexColor("#a8dadc"))
            self.drawRightString(w - MARGIN, h - 7.5*mm,
                self._info.get("target", "") + "  |  CONFIDENTIAL")

        # Footer
        self.setFillColor(C_LIGHT_BG)
        self.rect(0, 0, w, 10*mm, fill=1, stroke=0)
        self.setStrokeColor(C_BORDER)
        self.setLineWidth(0.3)
        self.line(0, 10*mm, w, 10*mm)
        self.setFont("Helvetica", 7)
        self.setFillColor(C_MUTED)
        self.drawString(MARGIN, 3.5*mm, "Generated by GREYPHANTOM  •  Automated Pentest Framework  •  CONFIDENTIAL")
        self.drawRightString(w - MARGIN, 3.5*mm, f"Page {p} of {total}")


# ── Stiller ───────────────────────────────────────────────────────────────────
def make_styles():
    def s(name, **kw):
        return ParagraphStyle(name, **kw)
    return {
        "section":   s("section", fontName="Helvetica-Bold", fontSize=13,
                        textColor=C_DARK, spaceBefore=14, spaceAfter=6),
        "body":      s("body", fontName="Helvetica", fontSize=9,
                        textColor=C_TEXT, leading=14, spaceAfter=4),
        "bold":      s("bold", fontName="Helvetica-Bold", fontSize=9,
                        textColor=C_TEXT, leading=14),
        "muted":     s("muted", fontName="Helvetica", fontSize=8,
                        textColor=C_MUTED, leading=12),
        "code":      s("code", fontName="Courier", fontSize=8,
                        textColor=HexColor("#1e3a5f"),
                        backColor=HexColor("#eef2f7"),
                        leading=12, leftIndent=6, rightIndent=6,
                        spaceBefore=3, spaceAfter=3),
        "th":        s("th", fontName="Helvetica-Bold", fontSize=8,
                        textColor=C_WHITE),
        "tc":        s("tc", fontName="Helvetica", fontSize=8,
                        textColor=C_TEXT, leading=11),
        "badge":     s("badge", fontName="Helvetica-Bold", fontSize=8,
                        alignment=TA_CENTER),
    }


def section_header(title, ST, story):
    story.append(Spacer(1, 3*mm))
    story.append(HRFlowable(width="100%", thickness=0.3, color=C_ACCENT, spaceAfter=2))
    story.append(Paragraph(title, ST["section"]))


def badge_cell(text, sev, ST):
    fg, bg = sev_color(sev)
    p = Paragraph(f'<b>{text}</b>', ST["badge"])
    return Table([[p]], colWidths=[22*mm],
        style=TableStyle([
            ("BACKGROUND", (0,0), (-1,-1), bg),
            ("TEXTCOLOR",  (0,0), (-1,-1), fg),
            ("ALIGN",      (0,0), (-1,-1), "CENTER"),
            ("VALIGN",     (0,0), (-1,-1), "MIDDLE"),
            ("TOPPADDING",    (0,0), (-1,-1), 3),
            ("BOTTOMPADDING", (0,0), (-1,-1), 3),
        ]))


def finding_card(f, ST, story, col_w):
    sev  = f.get("severity", "INFO").upper()
    fg, bg = sev_color(sev)

    # Başlık
    header = Table([[
        badge_cell(sev, sev, ST),
        Paragraph(f.get("title", ""), ST["bold"]),
        Paragraph(f'<b>CVSS {f.get("cvss", "N/A")}</b>', ST["bold"]),
    ]], colWidths=[24*mm, col_w - 46*mm, 22*mm],
    style=TableStyle([
        ("BACKGROUND", (0,0), (-1,-1), bg),
        ("VALIGN",     (0,0), (-1,-1), "MIDDLE"),
        ("LEFTPADDING",  (0,0), (-1,-1), 4),
        ("RIGHTPADDING", (0,0), (-1,-1), 4),
        ("TOPPADDING",   (0,0), (-1,-1), 5),
        ("BOTTOMPADDING",(0,0), (-1,-1), 5),
        ("LINEBELOW", (0,0), (-1,-1), 0.5, fg),
    ]))

    # Meta
    meta_rows = []
    if f.get("host"):
        meta_rows.append([Paragraph("Host", ST["muted"]), Paragraph(f["host"], ST["tc"])])
    if f.get("cwe"):
        meta_rows.append([Paragraph("CWE", ST["muted"]), Paragraph(f["cwe"], ST["tc"])])
    if f.get("owasp"):
        meta_rows.append([Paragraph("OWASP", ST["muted"]), Paragraph(f["owasp"], ST["tc"])])

    meta = Table(meta_rows or [[Paragraph("", ST["muted"]), Paragraph("", ST["tc"])]],
        colWidths=[22*mm, col_w - 22*mm],
        style=TableStyle([
            ("BACKGROUND", (0,0), (-1,-1), C_WHITE),
            ("VALIGN",     (0,0), (-1,-1), "TOP"),
            ("LEFTPADDING",  (0,0), (-1,-1), 6),
            ("RIGHTPADDING", (0,0), (-1,-1), 6),
            ("TOPPADDING",   (0,0), (-1,-1), 3),
            ("BOTTOMPADDING",(0,0), (-1,-1), 3),
            ("LINEBELOW", (0,0), (-1,-2), 0.2, C_BORDER),
        ]))

    # Detay
    detail_rows = []
    for label, key in [("Description", "description"), ("Impact", "impact"), ("Recommendation", "recommendation")]:
        if f.get(key):
            detail_rows.append([Paragraph(f"<b>{label}</b>", ST["muted"]),
                                 Paragraph(f[key], ST["tc"])])

    detail = Table(detail_rows or [[Paragraph("", ST["muted"]), Paragraph("", ST["tc"])]],
        colWidths=[28*mm, col_w - 28*mm],
        style=TableStyle([
            ("BACKGROUND", (0,0), (-1,-1), C_WHITE),
            ("VALIGN",     (0,0), (-1,-1), "TOP"),
            ("LEFTPADDING",  (0,0), (-1,-1), 6),
            ("RIGHTPADDING", (0,0), (-1,-1), 6),
            ("TOPPADDING",   (0,0), (-1,-1), 3),
            ("BOTTOMPADDING",(0,0), (-1,-1), 3),
            ("LINEBELOW", (0,0), (-1,-2), 0.2, C_BORDER),
        ]))

    rows = [[header], [meta], [detail]]

    # PoC
    if f.get("poc"):
        poc = Table([[Paragraph(f["poc"], ST["code"])]],
            colWidths=[col_w],
            style=TableStyle([
                ("BACKGROUND", (0,0), (-1,-1), HexColor("#eef2f7")),
                ("LEFTPADDING",  (0,0), (-1,-1), 6),
                ("RIGHTPADDING", (0,0), (-1,-1), 6),
                ("TOPPADDING",   (0,0), (-1,-1), 4),
                ("BOTTOMPADDING",(0,0), (-1,-1), 4),
                ("LINEABOVE", (0,0), (-1,-1), 0.2, C_BORDER),
            ]))
        rows.append([poc])

    outer = Table(rows, colWidths=[col_w],
        style=TableStyle([
            ("BOX",    (0,0), (-1,-1), 0.5, C_BORDER),
            ("LEFTPADDING",  (0,0), (-1,-1), 0),
            ("RIGHTPADDING", (0,0), (-1,-1), 0),
            ("TOPPADDING",   (0,0), (-1,-1), 0),
            ("BOTTOMPADDING",(0,0), (-1,-1), 0),
        ]))

    story.append(KeepTogether(outer))
    story.append(Spacer(1, 4*mm))


def extract_findings(results: dict) -> list[dict]:
    """JSON sonuçlarından bulgu listesi çıkar."""
    findings = []
    fid = 1

    # Nuclei bulgular
    for n in results.get("nuclei_findings", []):
        sev = n.get("severity", "info").upper()
        findings.append({
            "id":             f"GP-{fid:03d}",
            "severity":       sev,
            "cvss":           {"CRITICAL":"9.0","HIGH":"7.0","MEDIUM":"5.0","LOW":"3.0","INFO":"0.0"}.get(sev, "0.0"),
            "title":          n.get("name", n.get("template-id", "Nuclei Finding")),
            "host":           n.get("host", ""),
            "cwe":            "CWE-" + n.get("template-id", ""),
            "owasp":          "",
            "description":    n.get("description", "Nuclei template match"),
            "impact":         f"Security misconfiguration detected: {n.get('template-id','')}",
            "recommendation": "Review and remediate the identified misconfiguration",
            "poc":            f"Template: {n.get('template-id','')}\nURL: {n.get('url','')}",
        })
        fid += 1

    # Sensitive data
    for s in results.get("secret_findings", []):
        sev = s.get("severity", "HIGH").upper()
        findings.append({
            "id":             f"GP-{fid:03d}",
            "severity":       sev,
            "cvss":           "9.1" if sev == "CRITICAL" else "7.5",
            "title":          f"Sensitive Data Exposure — {s.get('type','')}",
            "host":           s.get("url", ""),
            "cwe":            "CWE-200",
            "owasp":          "A02:2021 — Cryptographic Failures",
            "description":    f"Sensitive data detected in API response: {s.get('type','')}",
            "impact":         "Exposed credentials or API keys can be used by attackers to access external services",
            "recommendation": "Remove sensitive data from API responses. Encrypt at rest and in transit.",
            "poc":            f"Value: {s.get('value', '')}\nEndpoint: {s.get('url','')}",
        })
        fid += 1

    # Auth findings
    rate = results.get("rate_limit", {})
    if rate and not rate.get("blocked"):
        findings.append({
            "id":             f"GP-{fid:03d}",
            "severity":       "HIGH",
            "cvss":           "7.5",
            "title":          "Missing Rate Limiting — Brute Force Possible",
            "host":           results.get("login_endpoint", "/api/auth/login"),
            "cwe":            "CWE-307",
            "owasp":          "A07:2021 — Identification and Authentication Failures",
            "description":    "The login endpoint does not implement rate limiting. An attacker can send unlimited authentication requests.",
            "impact":         "Allows brute force attacks against user accounts. Admin credentials may be compromised.",
            "recommendation": "Implement rate limiting (max 5 attempts per minute per IP). Add account lockout after failed attempts.",
            "poc":            "20 rapid requests sent — none blocked\nHTTP 200 returned for all attempts",
        })
        fid += 1

    for d in results.get("default_creds", []):
        findings.append({
            "id":             f"GP-{fid:03d}",
            "severity":       "CRITICAL",
            "cvss":           "9.8",
            "title":          "Default Credentials Accepted",
            "host":           d.get("url", ""),
            "cwe":            "CWE-1391",
            "owasp":          "A07:2021 — Identification and Authentication Failures",
            "description":    f"Default credentials {d.get('username')}:{d.get('password')} accepted",
            "impact":         "Full authentication bypass. Attacker gains admin access.",
            "recommendation": "Change all default credentials immediately.",
            "poc":            f"Username: {d.get('username')}\nPassword: {d.get('password')}\nResponse: {d.get('response','')[:100]}",
        })
        fid += 1

    # HTTP method findings
    for m in results.get("method_findings", []):
        if m.get("status") == 200 and m.get("method") not in ("GET", "HEAD", "OPTIONS"):
            findings.append({
                "id":             f"GP-{fid:03d}",
                "severity":       "HIGH",
                "cvss":           "7.3",
                "title":          f"Unexpected HTTP Method Allowed — {m.get('method')}",
                "host":           m.get("url", ""),
                "cwe":            "CWE-650",
                "owasp":          "A01:2021 — Broken Access Control",
                "description":    f"HTTP {m.get('method')} method accepted on {m.get('url')}",
                "impact":         "Unauthorized data modification may be possible",
                "recommendation": "Restrict allowed HTTP methods to only what is required",
                "poc":            f"Method: {m.get('method')}\nURL: {m.get('url')}\nStatus: {m.get('status')}",
            })
            fid += 1

    # IDOR
    for i in results.get("idor_findings", []):
        findings.append({
            "id":             f"GP-{fid:03d}",
            "severity":       "HIGH",
            "cvss":           "7.5",
            "title":          "Insecure Direct Object Reference (IDOR)",
            "host":           i.get("url", ""),
            "cwe":            "CWE-639",
            "owasp":          "API3:2023 — Broken Object Property Level Authorization",
            "description":    f"Object accessible without ownership validation: {i.get('url','')}",
            "impact":         "Unauthorized access to other users' data",
            "recommendation": "Implement server-side ownership checks on all object access",
            "poc":            f"URL: {i.get('url','')}\nNote: {i.get('note','')}",
        })
        fid += 1

    # Info endpoints
    for ep in results.get("info_endpoints", []):
        sev = ep.get("severity", "MEDIUM")
        findings.append({
            "id":             f"GP-{fid:03d}",
            "severity":       sev,
            "cvss":           "5.3" if sev == "MEDIUM" else "7.5",
            "title":          f"Sensitive File/Endpoint Exposed — {ep.get('url','').split('/')[-1]}",
            "host":           ep.get("url", ""),
            "cwe":            "CWE-538",
            "owasp":          "A05:2021 — Security Misconfiguration",
            "description":    f"Sensitive file accessible: {ep.get('url','')}. {ep.get('note','')}",
            "impact":         "Configuration data, credentials or source code may be exposed",
            "recommendation": "Remove or restrict access to sensitive files and endpoints",
            "poc":            f"URL: {ep.get('url','')}\nHTTP Status: {ep.get('status','')}",
        })
        fid += 1

    # GraphQL
    gql = results.get("graphql", {})
    if gql.get("introspection"):
        findings.append({
            "id":             f"GP-{fid:03d}",
            "severity":       "MEDIUM",
            "cvss":           "5.3",
            "title":          "GraphQL Introspection Enabled",
            "host":           gql.get("endpoint", "/graphql"),
            "cwe":            "CWE-200",
            "owasp":          "A05:2021 — Security Misconfiguration",
            "description":    "GraphQL introspection is enabled, exposing the full API schema",
            "impact":         "Attackers can enumerate all queries, mutations and types",
            "recommendation": "Disable introspection in production environments",
            "poc":            f"Endpoint: {gql.get('endpoint','')}\nTypes: {', '.join(gql.get('types',[])[:5])}",
        })
        fid += 1

    # CORS
    for c in results.get("cors_advanced", []):
        sev = c.get("severity", "MEDIUM")
        findings.append({
            "id":             f"GP-{fid:03d}",
            "severity":       sev,
            "cvss":           "7.4" if sev == "HIGH" else "5.4",
            "title":          f"CORS Misconfiguration — {c.get('type','')}",
            "host":           c.get("url", ""),
            "cwe":            "CWE-942",
            "owasp":          "A05:2021 — Security Misconfiguration",
            "description":    c.get("note", "CORS policy misconfiguration detected"),
            "impact":         "Cross-origin requests may steal sensitive data or session tokens",
            "recommendation": "Restrict CORS to trusted origins. Never use wildcard with credentials.",
            "poc":            f"Origin: {c.get('origin','')}\nACCESS-CONTROL-ALLOW-ORIGIN: {c.get('acao','')}",
        })
        fid += 1

    # SSL/TLS
    testssl = results.get("testssl", {})
    ssl_high = [f for f in testssl.get("findings", []) if f.get("severity") in ("HIGH", "CRITICAL")]
    for s in ssl_high[:3]:
        findings.append({
            "id":             f"GP-{fid:03d}",
            "severity":       s.get("severity", "MEDIUM"),
            "cvss":           "5.9",
            "title":          f"TLS/SSL Vulnerability — {s.get('id','')}",
            "host":           "",
            "cwe":            "CWE-326",
            "owasp":          "A02:2021 — Cryptographic Failures",
            "description":    s.get("finding", ""),
            "impact":         "Encrypted traffic may be intercepted or decrypted",
            "recommendation": "Disable vulnerable protocols and cipher suites. Use TLS 1.2+ only.",
            "poc":            f"Finding: {s.get('finding','')[:200]}",
        })
        fid += 1

    # Nmap — açık portlar
    ports = results.get("open_ports", {})
    for host, port_list in ports.items():
        for port in port_list:
            if any(p in str(port) for p in ["3306", "5432", "27017", "6379"]):
                findings.append({
                    "id":             f"GP-{fid:03d}",
                    "severity":       "HIGH",
                    "cvss":           "7.5",
                    "title":          f"Database Port Exposed to Internet — {port}",
                    "host":           host,
                    "cwe":            "CWE-284",
                    "owasp":          "A05:2021 — Security Misconfiguration",
                    "description":    f"Database service port {port} is accessible from the internet on {host}",
                    "impact":         "Direct database access attempts possible. Brute force and exploitation risk.",
                    "recommendation": "Restrict database ports to internal network only using firewall rules.",
                    "poc":            f"Port: {port}\nHost: {host}\nnmap: open",
                })
                fid += 1

    # Severity sıralama
    findings.sort(key=lambda x: sev_order(x.get("severity", "INFO")))
    return findings


def build_pdf(json_path: str, output_path: str = None) -> str:
    """JSON rapor dosyasından PDF üret."""
    with open(json_path) as f:
        data = json.load(f)

    meta    = data.get("meta", {})
    results = data.get("results", {})
    today   = datetime.date.today().strftime("%d %B %Y")
    target  = meta.get("target", "Unknown Target")

    if not output_path:
        output_path = json_path.replace(".json", ".pdf")

    doc_info = {"target": target, "date": today}

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=20*mm, bottomMargin=16*mm,
        title=f"GREYPHANTOM — {target}",
        author="GREYPHANTOM",
    )

    ST     = make_styles()
    col_w  = PAGE_W - 2 * MARGIN
    story  = []
    findings = extract_findings(results)

    # Severity sayıları
    counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "INFO": 0}
    for f in findings:
        sev = f.get("severity", "INFO").upper()
        counts[sev] = counts.get(sev, 0) + 1

    # ────────────────────────────────────────────────────────────────────────
    # KAPAK
    # ────────────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 55*mm))

    # Engagement tablosu
    eng_data = [
        ["Target",       target],
        ["Assessment",   "Web Application Penetration Test"],
        ["Mode",         meta.get("mode", "full").upper() + (" — AGGRESSIVE" if meta.get("aggressive") else " — PASSIVE")],
        ["Report Date",  today],
        ["Tool",         "GREYPHANTOM Automated Pentest Framework"],
        ["Version",      "1.0 — Final"],
        ["Classification","CONFIDENTIAL"],
    ]
    eng_table = Table(eng_data, colWidths=[42*mm, col_w - 42*mm],
        style=TableStyle([
            ("BACKGROUND", (0,0), (0,-1), C_DARK),
            ("TEXTCOLOR",  (0,0), (0,-1), HexColor("#a8dadc")),
            ("BACKGROUND", (1,0), (1,-1), C_WHITE),
            ("FONTNAME",   (0,0), (0,-1), "Helvetica-Bold"),
            ("FONTNAME",   (1,0), (1,-1), "Helvetica"),
            ("FONTSIZE",   (0,0), (-1,-1), 8),
            ("LEADING",    (0,0), (-1,-1), 13),
            ("TOPPADDING",    (0,0), (-1,-1), 5),
            ("BOTTOMPADDING", (0,0), (-1,-1), 5),
            ("LEFTPADDING",   (0,0), (-1,-1), 8),
            ("GRID", (0,0), (-1,-1), 0.3, C_BORDER),
        ]))
    story.append(eng_table)
    story.append(Spacer(1, 8*mm))

    # Risk özeti
    risk_data = [
        [Paragraph(f"<b>{s}</b>", ST["badge"]) for s in ["CRITICAL","HIGH","MEDIUM","LOW","INFO","TOTAL"]],
        [Paragraph(f"<b>{counts[s]}</b>", ParagraphStyle("v",
            fontName="Helvetica-Bold", fontSize=18,
            textColor=sev_color(s)[0], alignment=TA_CENTER))
         for s in ["CRITICAL","HIGH","MEDIUM","LOW","INFO"]] +
        [Paragraph(f"<b>{sum(counts.values())}</b>", ParagraphStyle("vt",
            fontName="Helvetica-Bold", fontSize=18,
            textColor=C_DARK, alignment=TA_CENTER))],
    ]
    cw = col_w / 6
    risk_table = Table(risk_data, colWidths=[cw]*6,
        style=TableStyle([
            ("BACKGROUND", (0,0), (0,0), C_CRIT_BG),
            ("BACKGROUND", (1,0), (1,0), C_HIGH_BG),
            ("BACKGROUND", (2,0), (2,0), C_MED_BG),
            ("BACKGROUND", (3,0), (3,0), C_LOW_BG),
            ("BACKGROUND", (4,0), (4,0), C_INFO_BG),
            ("BACKGROUND", (5,0), (5,0), C_LIGHT_BG),
            ("BACKGROUND", (0,1), (0,1), C_CRIT_BG),
            ("BACKGROUND", (1,1), (1,1), C_HIGH_BG),
            ("BACKGROUND", (2,1), (2,1), C_MED_BG),
            ("BACKGROUND", (3,1), (3,1), C_LOW_BG),
            ("BACKGROUND", (4,1), (4,1), C_INFO_BG),
            ("BACKGROUND", (5,1), (5,1), C_LIGHT_BG),
            ("TEXTCOLOR",  (0,0), (0,0), C_CRIT),
            ("TEXTCOLOR",  (1,0), (1,0), C_HIGH),
            ("TEXTCOLOR",  (2,0), (2,0), C_MED),
            ("TEXTCOLOR",  (3,0), (3,0), C_LOW),
            ("TEXTCOLOR",  (4,0), (4,0), C_INFO),
            ("TEXTCOLOR",  (5,0), (5,0), C_DARK),
            ("FONTNAME",   (0,0), (-1,0), "Helvetica-Bold"),
            ("FONTSIZE",   (0,0), (-1,0), 8),
            ("ALIGN",      (0,0), (-1,-1), "CENTER"),
            ("VALIGN",     (0,0), (-1,-1), "MIDDLE"),
            ("TOPPADDING",    (0,0), (-1,-1), 6),
            ("BOTTOMPADDING", (0,0), (-1,-1), 6),
            ("GRID", (0,0), (-1,-1), 0.3, C_BORDER),
            ("BOX",  (0,0), (-1,-1), 0.5, C_BORDER),
        ]))
    story.append(risk_table)

    # ────────────────────────────────────────────────────────────────────────
    # EXECUTIVE SUMMARY
    # ────────────────────────────────────────────────────────────────────────
    story.append(PageBreak())
    section_header("1. Executive Summary", ST, story)

    alive = results.get("alive_hosts", [])
    subs  = results.get("subdomains", [])
    story.append(Paragraph(
        f"GREYPHANTOM conducted an automated penetration test against <b>{target}</b>. "
        f"The assessment identified <b>{sum(counts.values())} security findings</b> across "
        f"{len(alive)} live host(s) and {len(subs)} subdomain(s). "
        f"The overall security posture is rated "
        f"<b>{'CRITICAL' if counts['CRITICAL'] > 0 else 'HIGH' if counts['HIGH'] > 0 else 'MEDIUM'}</b>.",
        ST["body"]))

    story.append(Spacer(1, 3*mm))
    story.append(Paragraph(
        "Immediate remediation is required for all CRITICAL and HIGH severity findings. "
        "MEDIUM severity findings should be addressed within the next development sprint.",
        ST["body"]))

    # ────────────────────────────────────────────────────────────────────────
    # SCOPE & METHODOLOGY
    # ────────────────────────────────────────────────────────────────────────
    section_header("2. Scope &amp; Methodology", ST, story)

    ports = results.get("open_ports", {})
    scope_data = [
        [Paragraph("<b>Asset</b>", ST["th"]),
         Paragraph("<b>Type</b>", ST["th"]),
         Paragraph("<b>Status</b>", ST["th"])],
        [target, "Web Application", "In Scope"],
    ]
    for host, port_list in ports.items():
        for port in port_list:
            scope_data.append([f"{host}:{port}", "Network Service", "In Scope"])

    scope_table = Table(scope_data,
        colWidths=[col_w*0.45, col_w*0.30, col_w*0.25],
        style=TableStyle([
            ("BACKGROUND", (0,0), (-1,0), C_DARK),
            ("FONTSIZE",   (0,0), (-1,-1), 8),
            ("LEADING",    (0,0), (-1,-1), 12),
            ("ROWBACKGROUNDS", (0,1), (-1,-1), [C_WHITE, C_LIGHT_BG]),
            ("TOPPADDING",    (0,0), (-1,-1), 5),
            ("BOTTOMPADDING", (0,0), (-1,-1), 5),
            ("LEFTPADDING",   (0,0), (-1,-1), 6),
            ("GRID", (0,0), (-1,-1), 0.3, C_BORDER),
        ]))
    story.append(scope_table)
    story.append(Spacer(1, 3*mm))
    story.append(Paragraph(
        "Testing methodology follows OWASP Testing Guide v4.2 and PTES. "
        "Tools: GREYPHANTOM (subfinder, httpx, nmap, nuclei, ffuf, katana, dalfox, sqlmap, testssl.sh).",
        ST["body"]))

    # ────────────────────────────────────────────────────────────────────────
    # DETAILED FINDINGS
    # ────────────────────────────────────────────────────────────────────────
    story.append(PageBreak())
    section_header("3. Detailed Findings", ST, story)

    if findings:
        for f in findings:
            finding_card(f, ST, story, col_w)
    else:
        story.append(Paragraph("No significant findings identified.", ST["body"]))

    # ────────────────────────────────────────────────────────────────────────
    # FINDINGS SUMMARY TABLE
    # ────────────────────────────────────────────────────────────────────────
    story.append(PageBreak())
    section_header("4. Findings Summary", ST, story)

    header_row = [
        Paragraph("<b>ID</b>", ST["th"]),
        Paragraph("<b>Severity</b>", ST["th"]),
        Paragraph("<b>CVSS</b>", ST["th"]),
        Paragraph("<b>Title</b>", ST["th"]),
        Paragraph("<b>Status</b>", ST["th"]),
    ]
    rows = [header_row]
    for f in findings:
        sev = f.get("severity","INFO").upper()
        fg, _ = sev_color(sev)
        rows.append([
            Paragraph(f.get("id",""), ST["tc"]),
            Paragraph(f'<font color="#{fg.hexval()[1:]}"><b>{sev}</b></font>', ST["tc"]),
            Paragraph(str(f.get("cvss","N/A")), ST["tc"]),
            Paragraph(f.get("title",""), ST["tc"]),
            Paragraph("Open", ST["tc"]),
        ])

    sum_table = Table(rows,
        colWidths=[18*mm, 22*mm, 14*mm, col_w - 18*mm - 22*mm - 14*mm - 18*mm, 18*mm],
        style=TableStyle([
            ("BACKGROUND", (0,0), (-1,0), C_DARK),
            ("TEXTCOLOR",  (0,0), (-1,0), C_WHITE),
            ("FONTSIZE",   (0,0), (-1,-1), 8),
            ("LEADING",    (0,0), (-1,-1), 11),
            ("ROWBACKGROUNDS", (0,1), (-1,-1), [C_WHITE, C_LIGHT_BG]),
            ("TOPPADDING",    (0,0), (-1,-1), 4),
            ("BOTTOMPADDING", (0,0), (-1,-1), 4),
            ("LEFTPADDING",   (0,0), (-1,-1), 5),
            ("GRID", (0,0), (-1,-1), 0.3, C_BORDER),
            ("BOX",  (0,0), (-1,-1), 0.5, C_BORDER),
        ]))
    story.append(sum_table)

    # ────────────────────────────────────────────────────────────────────────
    # REMEDIATION ROADMAP
    # ────────────────────────────────────────────────────────────────────────
    section_header("5. Remediation Roadmap", ST, story)

    rm_data = [
        [Paragraph("<b>Priority</b>", ST["th"]),
         Paragraph("<b>Severity</b>", ST["th"]),
         Paragraph("<b>Deadline</b>", ST["th"]),
         Paragraph("<b>Count</b>", ST["th"])],
        ["Immediate (P0)", "CRITICAL", "Within 48 hours", str(counts["CRITICAL"])],
        ["Short-term (P1)", "HIGH",     "Within 14 days",  str(counts["HIGH"])],
        ["Sprint (P2)",    "MEDIUM",   "Next sprint",      str(counts["MEDIUM"])],
        ["Backlog (P3)",   "LOW/INFO", "Within 60 days",   str(counts["LOW"] + counts["INFO"])],
    ]
    rm_table = Table(rm_data,
        colWidths=[35*mm, 30*mm, 40*mm, col_w - 35*mm - 30*mm - 40*mm],
        style=TableStyle([
            ("BACKGROUND", (0,0), (-1,0), C_DARK),
            ("TEXTCOLOR",  (0,0), (-1,0), C_WHITE),
            ("FONTSIZE",   (0,0), (-1,-1), 8),
            ("LEADING",    (0,0), (-1,-1), 12),
            ("ROWBACKGROUNDS", (0,1), (-1,-1), [C_CRIT_BG, C_HIGH_BG, C_MED_BG, C_LOW_BG]),
            ("TOPPADDING",    (0,0), (-1,-1), 5),
            ("BOTTOMPADDING", (0,0), (-1,-1), 5),
            ("LEFTPADDING",   (0,0), (-1,-1), 6),
            ("GRID", (0,0), (-1,-1), 0.3, C_BORDER),
            ("BOX",  (0,0), (-1,-1), 0.5, C_BORDER),
        ]))
    story.append(rm_table)

    # ── İmza ──────────────────────────────────────────────────────────────
    story.append(Spacer(1, 10*mm))
    story.append(HRFlowable(width="100%", thickness=0.3, color=C_BORDER))
    story.append(Spacer(1, 4*mm))
    sig_data = [[
        Paragraph(f"<b>Generated by</b><br/>GREYPHANTOM v3<br/>Automated Pentest Framework", ST["body"]),
        Paragraph(f"<b>Report Date</b><br/>{today}<br/><br/><i>AI-assisted, human-validated</i>", ST["body"]),
    ]]
    sig_table = Table(sig_data, colWidths=[col_w/2]*2,
        style=TableStyle([
            ("VALIGN", (0,0), (-1,-1), "TOP"),
            ("LEFTPADDING",  (0,0), (-1,-1), 0),
            ("RIGHTPADDING", (0,0), (-1,-1), 8),
        ]))
    story.append(sig_table)

    # ── Build ────────────────────────────────────────────────────────────
    class MyCanvas(ReportCanvas):
        def __init__(self, filename, **kwargs):
            kwargs.pop("doc_info", None)
            ReportCanvas.__init__(self, filename, doc_info=doc_info, **kwargs)

    doc.build(story, canvasmaker=MyCanvas)
    return output_path